name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: >
          Thank you for your contribution.  Development happens in the
          [DIY repo](https://gitlab.kitware.com/diatomic/diy)
          on Kitware's GitLab.  Please submit merge requests there.
